apiVersion: v1
kind: Namespace
metadata:
  name: nagp-dev
  labels:
    app.kubernetes.io/part-of: nagp-multi-tier
    environment: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nagp-quota
  namespace: nagp-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "4"
    limits.memory: 6Gi
    pods: "20"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: nagp-dev
data:
  SPRING_PROFILES_ACTIVE: dev
  ENVIRONMENT_NAME: dev
  DB_HOST: postgres.nagp-dev.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: catalog_dev_db
  DB_POOL_MAX_SIZE: "6"
  DB_POOL_MIN_IDLE: "1"
  FLYWAY_ENABLED: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nagp-dev
type: Opaque
data:
  POSTGRES_USER: Y2F0YWxvZ19kZXZfdXNlcg==
  POSTGRES_PASSWORD: Y2F0YWxvZ19kZXZfcGFzc18yMDI2
  POSTGRES_DB: Y2F0YWxvZ19kZXZfZGI=
---
apiVersion: v1
kind: Secret
metadata:
  name: api-db-secret
  namespace: nagp-dev
type: Opaque
data:
  DB_USERNAME: Y2F0YWxvZ19kZXZfdXNlcg==
  DB_PASSWORD: Y2F0YWxvZ19kZXZfcGFzc18yMDI2
