apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nagp
type: Opaque
data:
  POSTGRES_USER: Y2F0YWxvZ191c2Vy
  POSTGRES_PASSWORD: Y2F0YWxvZ19wYXNzXzIwMjY=
  POSTGRES_DB: Y2F0YWxvZ2Ri
---
apiVersion: v1
kind: Secret
metadata:
  name: api-db-secret
  namespace: nagp
type: Opaque
data:
  DB_USERNAME: Y2F0YWxvZ191c2Vy
  DB_PASSWORD: Y2F0YWxvZ19wYXNzXzIwMjY=
